{% set name = "alleleflux" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MoellerLabPU/AlleleFlux/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: <update after creating release tag>

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=64.0.0
    - wheel
  run:
    - python >=3.7
    # Core scientific stack (conda-forge)
    - numpy
    - pandas
    - scipy
    - matplotlib-base
    - seaborn
    - statsmodels
    - tqdm
    - intervaltree
    # Bioinformatics (bioconda)
    - pysam
    - biopython
    # Workflow management (bioconda)
    - snakemake-minimal >=8.0.0
    - snakemake-executor-plugin-cluster-generic
    # R integration (conda-forge)
    - rpy2
    - r-base
    - r-tidyr

test:
  imports:
    - alleleflux
    - alleleflux.scripts.analysis
    - alleleflux.scripts.preprocessing
    - alleleflux.scripts.statistics
  commands:
    - alleleflux --help
    - alleleflux-profile --help
    - alleleflux-qc --help
    - alleleflux-scores --help
    - alleleflux-cmh --help

about:
  home: https://github.com/MoellerLabPU/AlleleFlux
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A tool for fine-grained evolutionary analysis of microbial populations and communities
  description: |
    AlleleFlux is a python package for analyzing allele frequencies 
    in metagenomic data. It profiles MAG (Metagenome-Assembled Genome) populations 
    across samples, detecting parallel evolution through allele frequency changes.
  dev_url: https://github.com/MoellerLabPU/AlleleFlux
  doc_url: https://github.com/MoellerLabPU/AlleleFlux

extra:
  recipe-maintainers:
    - sidd-uppal
